    tilepal 1, WATER, WATER, RED, RED, GREEN, GREEN, BROWN, BROWN
    tilepal 1, RED, RED, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY
    tilepal 1, WATER, WATER, RED, RED, GREEN, GREEN, BROWN, BROWN
    tilepal 1, RED, RED, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY
