; metatile layout constants
DEF FIRST_SPACE_METATILE        EQU $80
DEF FIRST_GREY_SPACE_METATILE   EQU $e0
DEF UNIQUE_SPACE_METATILES_MASK EQU %11111

; Branch Space special direction values
DEF BRANCH_DIRECTION_INVALID     EQU -1
DEF BRANCH_DIRECTION_UNAVAILABLE EQU -2