; technique constants
	const_def
	const TECHNIQUE_CUT_F
    const TECHNIQUE_FLASH_F
    const TECHNIQUE_SURF_F
    const TECHNIQUE_ROCK_SMASH_F
DEF NUM_TECHNIQUES EQU const_value

DEF TECHNIQUE_CUT        EQU 1 << TECHNIQUE_CUT_F
DEF TECHNIQUE_FLASH      EQU 1 << TECHNIQUE_FLASH_F
DEF TECHNIQUE_SURF       EQU 1 << TECHNIQUE_SURF_F
DEF TECHNIQUE_ROCK_SMASH EQU 1 << TECHNIQUE_ROCK_SMASH_F
